//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Input/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""RowingTest"",
            ""id"": ""9ea4a343-59ec-41bf-b12f-7d2f88525c3c"",
            ""actions"": [
                {
                    ""name"": ""CatchPress"",
                    ""type"": ""Button"",
                    ""id"": ""422b4de6-a9cd-4b0b-9f2f-ff29ff08c972"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CatchRelease"",
                    ""type"": ""Button"",
                    ""id"": ""4598b695-8247-4a21-95bf-a82d3a277ed0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""170d6c5e-221a-4abd-a74f-450a156b594a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RudderUpPress"",
                    ""type"": ""Button"",
                    ""id"": ""bbb434c4-eaea-46e9-aee2-df03574d2e65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RudderUpRelease"",
                    ""type"": ""Button"",
                    ""id"": ""c4af8940-d6e2-4515-b694-6f7364e12936"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RudderDownPress"",
                    ""type"": ""Button"",
                    ""id"": ""6c3f8857-a884-44aa-9fb6-62ed11018266"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RudderDownRelease"",
                    ""type"": ""Button"",
                    ""id"": ""dd09be05-ec8c-423b-a098-2ac3ae0d53ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReversePress"",
                    ""type"": ""Button"",
                    ""id"": ""7ace1d4d-477a-48b0-95b6-8df52609edda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReverseRelease"",
                    ""type"": ""Button"",
                    ""id"": ""b4118d9f-d7e0-4f4a-ac92-1f24a2d03e15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""f681e2bc-b25b-4327-8d5e-52aa2331a4f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2233b83e-8fea-437a-bd57-4ac3921ad223"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CatchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0b06e15-762b-497a-805f-be14369d05c3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58c517f4-f1e4-4860-b854-17fdafeefcf1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderUpPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2142eaa9-0db5-4b4f-92ab-dc03878e679d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderUpPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a18d17e4-b42d-430c-8a57-5cbc55feabc2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderDownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a94088b3-3915-4ba5-b771-b106c941f08e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderDownPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eecab7b1-cdd4-4ddc-9024-00767effc0e0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReversePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ce288ca-4b24-42a4-97b4-8cadb8a70dd9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b224c7e3-d346-462a-8d7d-7372a48b5419"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CatchRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7bb491-724d-4bf7-8eb9-28597dca1d23"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderUpRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58a43044-93d5-4580-bc7e-6f0909ff4b39"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderUpRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""103f4dae-bb3e-43db-a555-9a3cf67dd6d7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderDownRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfd616b3-a1ab-4038-a0a0-226298c84d8e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RudderDownRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a77c79-b0f3-4200-897d-ecdcc3eb6806"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReverseRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""IndieCade"",
            ""id"": ""81e276e4-6ae4-470c-b3c8-fc5d12c65ebb"",
            ""actions"": [
                {
                    ""name"": ""MovePlayerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""aff05734-f0f9-4534-8077-c73798032a21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2),Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePlayerRight"",
                    ""type"": ""Button"",
                    ""id"": ""7ec12e21-033d-4ad3-872d-82803eec0139"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePlayerUp"",
                    ""type"": ""Button"",
                    ""id"": ""fad7954c-8c73-4ea2-9897-3e249ab2c835"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovePlayerDown"",
                    ""type"": ""Button"",
                    ""id"": ""eceb05c5-5ec1-45bd-a40a-ed9cdec28ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3b8fd26c-4afd-4656-b688-78b5541b72e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RowingUp"",
                    ""type"": ""Button"",
                    ""id"": ""3a17a03a-5903-40b4-8d82-d34ae0d61cb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RowingDown"",
                    ""type"": ""Button"",
                    ""id"": ""26ccbf43-5356-4c41-b593-5a83c1b3ca74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RowingRight"",
                    ""type"": ""Button"",
                    ""id"": ""e9cf459c-9836-4391-8495-bc023b7b02b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RowingLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d91f3cdd-b196-4b89-a7a4-580ff1aeaca3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RowingShift"",
                    ""type"": ""Button"",
                    ""id"": ""073e2230-1435-419c-89fb-3e2075ee0854"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""66202889-6496-4b37-bfbb-6a17bd73e071"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b32b316-9eaa-463f-ad78-dba9c3c56533"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d4c14ed-2565-4a18-92cb-d4271cb1be80"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8307aed1-baf2-4505-8388-7b07cb14ba57"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23b627a6-b49f-4556-8656-5b5b1622203d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cda8b194-df73-47aa-81b9-dc9009ac31e5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c59843-91c0-4335-8053-db8299c99617"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d91eff9c-9b46-4555-aa44-d7b623486bba"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovePlayerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3209bc55-45a6-43ba-ad65-21de2b17bf81"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ac8d94e-59b1-4b12-9c6d-4e87b0b97aeb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""872f47a6-6083-4f15-bcc2-622823086566"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53f1838e-c5b4-4ecd-b86b-02660a5f9440"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4999ad02-9a14-4c22-8ee3-34e887a5ef1d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f7d17ba-6800-4e61-88a2-6da935d96b98"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbb730b4-f2f4-44a4-86ba-f5fdb93c17d6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a9ff28e-3497-4d7d-b9c1-956f000bb8d4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dbf8082-d822-47a8-8fca-eaa639bbdcd6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4573c3b4-7d48-402b-81d2-7ae9ed8db07b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RowingShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RowingTest
        m_RowingTest = asset.FindActionMap("RowingTest", throwIfNotFound: true);
        m_RowingTest_CatchPress = m_RowingTest.FindAction("CatchPress", throwIfNotFound: true);
        m_RowingTest_CatchRelease = m_RowingTest.FindAction("CatchRelease", throwIfNotFound: true);
        m_RowingTest_Inventory = m_RowingTest.FindAction("Inventory", throwIfNotFound: true);
        m_RowingTest_RudderUpPress = m_RowingTest.FindAction("RudderUpPress", throwIfNotFound: true);
        m_RowingTest_RudderUpRelease = m_RowingTest.FindAction("RudderUpRelease", throwIfNotFound: true);
        m_RowingTest_RudderDownPress = m_RowingTest.FindAction("RudderDownPress", throwIfNotFound: true);
        m_RowingTest_RudderDownRelease = m_RowingTest.FindAction("RudderDownRelease", throwIfNotFound: true);
        m_RowingTest_ReversePress = m_RowingTest.FindAction("ReversePress", throwIfNotFound: true);
        m_RowingTest_ReverseRelease = m_RowingTest.FindAction("ReverseRelease", throwIfNotFound: true);
        m_RowingTest_Interact = m_RowingTest.FindAction("Interact", throwIfNotFound: true);
        // IndieCade
        m_IndieCade = asset.FindActionMap("IndieCade", throwIfNotFound: true);
        m_IndieCade_MovePlayerLeft = m_IndieCade.FindAction("MovePlayerLeft", throwIfNotFound: true);
        m_IndieCade_MovePlayerRight = m_IndieCade.FindAction("MovePlayerRight", throwIfNotFound: true);
        m_IndieCade_MovePlayerUp = m_IndieCade.FindAction("MovePlayerUp", throwIfNotFound: true);
        m_IndieCade_MovePlayerDown = m_IndieCade.FindAction("MovePlayerDown", throwIfNotFound: true);
        m_IndieCade_Interact = m_IndieCade.FindAction("Interact", throwIfNotFound: true);
        m_IndieCade_RowingUp = m_IndieCade.FindAction("RowingUp", throwIfNotFound: true);
        m_IndieCade_RowingDown = m_IndieCade.FindAction("RowingDown", throwIfNotFound: true);
        m_IndieCade_RowingRight = m_IndieCade.FindAction("RowingRight", throwIfNotFound: true);
        m_IndieCade_RowingLeft = m_IndieCade.FindAction("RowingLeft", throwIfNotFound: true);
        m_IndieCade_RowingShift = m_IndieCade.FindAction("RowingShift", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RowingTest
    private readonly InputActionMap m_RowingTest;
    private IRowingTestActions m_RowingTestActionsCallbackInterface;
    private readonly InputAction m_RowingTest_CatchPress;
    private readonly InputAction m_RowingTest_CatchRelease;
    private readonly InputAction m_RowingTest_Inventory;
    private readonly InputAction m_RowingTest_RudderUpPress;
    private readonly InputAction m_RowingTest_RudderUpRelease;
    private readonly InputAction m_RowingTest_RudderDownPress;
    private readonly InputAction m_RowingTest_RudderDownRelease;
    private readonly InputAction m_RowingTest_ReversePress;
    private readonly InputAction m_RowingTest_ReverseRelease;
    private readonly InputAction m_RowingTest_Interact;
    public struct RowingTestActions
    {
        private @GameControls m_Wrapper;
        public RowingTestActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CatchPress => m_Wrapper.m_RowingTest_CatchPress;
        public InputAction @CatchRelease => m_Wrapper.m_RowingTest_CatchRelease;
        public InputAction @Inventory => m_Wrapper.m_RowingTest_Inventory;
        public InputAction @RudderUpPress => m_Wrapper.m_RowingTest_RudderUpPress;
        public InputAction @RudderUpRelease => m_Wrapper.m_RowingTest_RudderUpRelease;
        public InputAction @RudderDownPress => m_Wrapper.m_RowingTest_RudderDownPress;
        public InputAction @RudderDownRelease => m_Wrapper.m_RowingTest_RudderDownRelease;
        public InputAction @ReversePress => m_Wrapper.m_RowingTest_ReversePress;
        public InputAction @ReverseRelease => m_Wrapper.m_RowingTest_ReverseRelease;
        public InputAction @Interact => m_Wrapper.m_RowingTest_Interact;
        public InputActionMap Get() { return m_Wrapper.m_RowingTest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RowingTestActions set) { return set.Get(); }
        public void SetCallbacks(IRowingTestActions instance)
        {
            if (m_Wrapper.m_RowingTestActionsCallbackInterface != null)
            {
                @CatchPress.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchPress;
                @CatchPress.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchPress;
                @CatchPress.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchPress;
                @CatchRelease.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchRelease;
                @CatchRelease.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchRelease;
                @CatchRelease.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnCatchRelease;
                @Inventory.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInventory;
                @RudderUpPress.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpPress;
                @RudderUpPress.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpPress;
                @RudderUpPress.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpPress;
                @RudderUpRelease.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpRelease;
                @RudderUpRelease.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpRelease;
                @RudderUpRelease.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderUpRelease;
                @RudderDownPress.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownPress;
                @RudderDownPress.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownPress;
                @RudderDownPress.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownPress;
                @RudderDownRelease.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownRelease;
                @RudderDownRelease.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownRelease;
                @RudderDownRelease.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnRudderDownRelease;
                @ReversePress.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReversePress;
                @ReversePress.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReversePress;
                @ReversePress.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReversePress;
                @ReverseRelease.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReverseRelease;
                @ReverseRelease.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReverseRelease;
                @ReverseRelease.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnReverseRelease;
                @Interact.started -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_RowingTestActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_RowingTestActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CatchPress.started += instance.OnCatchPress;
                @CatchPress.performed += instance.OnCatchPress;
                @CatchPress.canceled += instance.OnCatchPress;
                @CatchRelease.started += instance.OnCatchRelease;
                @CatchRelease.performed += instance.OnCatchRelease;
                @CatchRelease.canceled += instance.OnCatchRelease;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @RudderUpPress.started += instance.OnRudderUpPress;
                @RudderUpPress.performed += instance.OnRudderUpPress;
                @RudderUpPress.canceled += instance.OnRudderUpPress;
                @RudderUpRelease.started += instance.OnRudderUpRelease;
                @RudderUpRelease.performed += instance.OnRudderUpRelease;
                @RudderUpRelease.canceled += instance.OnRudderUpRelease;
                @RudderDownPress.started += instance.OnRudderDownPress;
                @RudderDownPress.performed += instance.OnRudderDownPress;
                @RudderDownPress.canceled += instance.OnRudderDownPress;
                @RudderDownRelease.started += instance.OnRudderDownRelease;
                @RudderDownRelease.performed += instance.OnRudderDownRelease;
                @RudderDownRelease.canceled += instance.OnRudderDownRelease;
                @ReversePress.started += instance.OnReversePress;
                @ReversePress.performed += instance.OnReversePress;
                @ReversePress.canceled += instance.OnReversePress;
                @ReverseRelease.started += instance.OnReverseRelease;
                @ReverseRelease.performed += instance.OnReverseRelease;
                @ReverseRelease.canceled += instance.OnReverseRelease;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public RowingTestActions @RowingTest => new RowingTestActions(this);

    // IndieCade
    private readonly InputActionMap m_IndieCade;
    private IIndieCadeActions m_IndieCadeActionsCallbackInterface;
    private readonly InputAction m_IndieCade_MovePlayerLeft;
    private readonly InputAction m_IndieCade_MovePlayerRight;
    private readonly InputAction m_IndieCade_MovePlayerUp;
    private readonly InputAction m_IndieCade_MovePlayerDown;
    private readonly InputAction m_IndieCade_Interact;
    private readonly InputAction m_IndieCade_RowingUp;
    private readonly InputAction m_IndieCade_RowingDown;
    private readonly InputAction m_IndieCade_RowingRight;
    private readonly InputAction m_IndieCade_RowingLeft;
    private readonly InputAction m_IndieCade_RowingShift;
    public struct IndieCadeActions
    {
        private @GameControls m_Wrapper;
        public IndieCadeActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovePlayerLeft => m_Wrapper.m_IndieCade_MovePlayerLeft;
        public InputAction @MovePlayerRight => m_Wrapper.m_IndieCade_MovePlayerRight;
        public InputAction @MovePlayerUp => m_Wrapper.m_IndieCade_MovePlayerUp;
        public InputAction @MovePlayerDown => m_Wrapper.m_IndieCade_MovePlayerDown;
        public InputAction @Interact => m_Wrapper.m_IndieCade_Interact;
        public InputAction @RowingUp => m_Wrapper.m_IndieCade_RowingUp;
        public InputAction @RowingDown => m_Wrapper.m_IndieCade_RowingDown;
        public InputAction @RowingRight => m_Wrapper.m_IndieCade_RowingRight;
        public InputAction @RowingLeft => m_Wrapper.m_IndieCade_RowingLeft;
        public InputAction @RowingShift => m_Wrapper.m_IndieCade_RowingShift;
        public InputActionMap Get() { return m_Wrapper.m_IndieCade; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(IndieCadeActions set) { return set.Get(); }
        public void SetCallbacks(IIndieCadeActions instance)
        {
            if (m_Wrapper.m_IndieCadeActionsCallbackInterface != null)
            {
                @MovePlayerLeft.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerLeft;
                @MovePlayerLeft.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerLeft;
                @MovePlayerLeft.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerLeft;
                @MovePlayerRight.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerRight;
                @MovePlayerRight.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerRight;
                @MovePlayerRight.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerRight;
                @MovePlayerUp.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerUp;
                @MovePlayerUp.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerUp;
                @MovePlayerUp.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerUp;
                @MovePlayerDown.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerDown;
                @MovePlayerDown.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerDown;
                @MovePlayerDown.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnMovePlayerDown;
                @Interact.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnInteract;
                @RowingUp.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingUp;
                @RowingUp.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingUp;
                @RowingUp.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingUp;
                @RowingDown.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingDown;
                @RowingDown.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingDown;
                @RowingDown.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingDown;
                @RowingRight.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingRight;
                @RowingRight.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingRight;
                @RowingRight.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingRight;
                @RowingLeft.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingLeft;
                @RowingLeft.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingLeft;
                @RowingLeft.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingLeft;
                @RowingShift.started -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingShift;
                @RowingShift.performed -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingShift;
                @RowingShift.canceled -= m_Wrapper.m_IndieCadeActionsCallbackInterface.OnRowingShift;
            }
            m_Wrapper.m_IndieCadeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovePlayerLeft.started += instance.OnMovePlayerLeft;
                @MovePlayerLeft.performed += instance.OnMovePlayerLeft;
                @MovePlayerLeft.canceled += instance.OnMovePlayerLeft;
                @MovePlayerRight.started += instance.OnMovePlayerRight;
                @MovePlayerRight.performed += instance.OnMovePlayerRight;
                @MovePlayerRight.canceled += instance.OnMovePlayerRight;
                @MovePlayerUp.started += instance.OnMovePlayerUp;
                @MovePlayerUp.performed += instance.OnMovePlayerUp;
                @MovePlayerUp.canceled += instance.OnMovePlayerUp;
                @MovePlayerDown.started += instance.OnMovePlayerDown;
                @MovePlayerDown.performed += instance.OnMovePlayerDown;
                @MovePlayerDown.canceled += instance.OnMovePlayerDown;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @RowingUp.started += instance.OnRowingUp;
                @RowingUp.performed += instance.OnRowingUp;
                @RowingUp.canceled += instance.OnRowingUp;
                @RowingDown.started += instance.OnRowingDown;
                @RowingDown.performed += instance.OnRowingDown;
                @RowingDown.canceled += instance.OnRowingDown;
                @RowingRight.started += instance.OnRowingRight;
                @RowingRight.performed += instance.OnRowingRight;
                @RowingRight.canceled += instance.OnRowingRight;
                @RowingLeft.started += instance.OnRowingLeft;
                @RowingLeft.performed += instance.OnRowingLeft;
                @RowingLeft.canceled += instance.OnRowingLeft;
                @RowingShift.started += instance.OnRowingShift;
                @RowingShift.performed += instance.OnRowingShift;
                @RowingShift.canceled += instance.OnRowingShift;
            }
        }
    }
    public IndieCadeActions @IndieCade => new IndieCadeActions(this);
    public interface IRowingTestActions
    {
        void OnCatchPress(InputAction.CallbackContext context);
        void OnCatchRelease(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnRudderUpPress(InputAction.CallbackContext context);
        void OnRudderUpRelease(InputAction.CallbackContext context);
        void OnRudderDownPress(InputAction.CallbackContext context);
        void OnRudderDownRelease(InputAction.CallbackContext context);
        void OnReversePress(InputAction.CallbackContext context);
        void OnReverseRelease(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IIndieCadeActions
    {
        void OnMovePlayerLeft(InputAction.CallbackContext context);
        void OnMovePlayerRight(InputAction.CallbackContext context);
        void OnMovePlayerUp(InputAction.CallbackContext context);
        void OnMovePlayerDown(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnRowingUp(InputAction.CallbackContext context);
        void OnRowingDown(InputAction.CallbackContext context);
        void OnRowingRight(InputAction.CallbackContext context);
        void OnRowingLeft(InputAction.CallbackContext context);
        void OnRowingShift(InputAction.CallbackContext context);
    }
}
